laravel CRUD/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('eventcategory','EventCategoryController');
Route::resource('eventtopic','EventTopicController');
Route::resource('event','EventController');

laravel CRUD/app/EventCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventCategory extends Model
{
    protected $fillable = [
        'name'
    ];
}

laravel CRUD/app/Http/Controllers/EventCategoryController.php
<?php 


namespace App\Http\Controllers;

use App\EventCategory;
use Illuminate\Http\Request;

class EventCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     

    public function index()
    {
        $eventcategory = EventCategory::all();
        return view('eventcategory.index', compact('eventcategory'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('eventcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        EventCategory::create($request->all());
        return redirect()->route('eventcategory.index')

            ->with('success', 'EventCategory created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\EventCategory  $eventcategory
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $eventcategory = EventCategory::find($id);
        return view('eventcategory.readingone',array('eventcategory' => $eventcategory));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\EventCategory  $eventcategory
     * @return \Illuminate\Http\Response
     */
   
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\EventCategory  $eventcategory
     * @return \Illuminate\Http\Response
     */
    public function edit(EventCategory $eventcategory)
    {
        return view('eventcategory.updateone',compact('eventcategory'));
    }
    public function update(Request $request, EventCategory $eventcategory)
    {

        $request->validate([
            'name' => 'required' ,
        
        ]);

        $eventcategory->update($request->all());

        return redirect()->route('eventcategory.index')
            ->with('success','eventcategory updated successfully');
    }
   
  
     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
  
   
    public function destroy(EventCategory $eventcategory)

    {
          
          $eventcategory->delete();
       
        return redirect()->route('eventcategory.index')
         ->with('success' ,'Successfully deleted the EventCategory!');
    }



// die function om  return alle eventcategorys voor de event creat 
    public static function readall()
    {
      return  $eventcategory = EventCategory::all();
       
    }



}
   

laravel CRUD/resources/views/eventcategory/create.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New EventCategory</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('eventcategory.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('eventcategory.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

laravel CRUD/resources/views/eventcategory/index.blade.php
@extends('layout')  



@section('content' ) 

    <div class="row"> 
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 7 CRUD Fric-frac</h2>
               
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('eventcategory.create') }}"> Create New EventCategory</a>
                
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($eventcategory as $item)
        <tr>
            <td>{{ $item->id }}</td>
            <td>{{ $item->name }}</td>
            <td>


            <form action="{{ route('eventcategory.destroy',$item->id) }}" method="POST">


<a class="btn btn-info" href="{{ route('eventcategory.show',$item->id) }}">Show</a>


<a class="btn btn-primary"  href="{{ route('eventcategory.edit' ,$item->id) }}">Edit </a>

@csrf
@method('DELETE')

<button type="submit" class="btn btn-danger">Delete</button>
</form>

</td>
        </tr>
        @endforeach
    </table>
 @endsection

laravel CRUD/resources/views/eventcategory/readingone.blade.php
@extends('layout')
@section('content') 

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Reading: {{ $eventcategory->name }}</h2> 
       </div> 
       <br>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('eventcategory.index') }}"> Back</a>
        </div>
    </div>
</div> 

<table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Name</th>
           
        </tr> 

        <td>{{ $eventcategory->id }}</td>
            <td>{{ $eventcategory->name }}</td> 
        
    </div>
    </table>
    @endsection

laravel CRUD/resources/views/eventcategory/updateone.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New EventCategory</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('eventcategory.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('eventcategory.update' , $eventcategory->id) }}" method="POST">
    @csrf
    @method('PUT')
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
               
                <input type="text" name="name" class="form-control"  value="{{ $eventcategory->name }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection