laravel CRUD/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('eventcategory','EventCategoryController');
Route::resource('eventtopic','EventTopicController');
Route::resource('event','EventController');

laravel CRUD/app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'name' ,
        'Location',
        'Starts' ,
        'Ends' ,
        'Image' ,
        'Description' ,
        'OrganiserName' ,
        'OrganiserDescription' ,
        'EventCategoryId' ,
        'EventTopicId'
        
            
    ]; 

}

laravel CRUD/app/Http/Controllers/EventController.php
<?php 


namespace App\Http\Controllers;

use App\Event;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $event = Event::all();
        return view('event.index', compact('event'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $eventcategory = EventCategoryController::readall();
        $eventtopic = EventTopicController::readall();
        return view('event.create' ,compact('eventcategory'),compact('eventtopic') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'Location'=> 'required',
            'Starts' => 'required',
            'Ends' => 'required',
            'Image'=> 'required' ,
            'Description'=> 'required' ,
            'OrganiserName'=> 'required' ,
            'OrganiserDescription'=> 'required' ,
            'EventCategoryId'=> 'required' ,
            'EventTopicId'=> 'required' ,
        ]);
        Event::create($request->all());
        return redirect()->route('event.index')

            ->with('success', 'Event created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::find($id);
        return view('event.readingone',array('event' => $event));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event $event
     * @return \Illuminate\Http\Response
     */
   
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        $eventcategory = EventCategoryController::readall();
        $eventtopic = EventTopicController::readall();
        return view('event.updateone',compact('event') ,compact('eventcategory'),compact('eventtopic') );
        

    }
    public function update(Request $request, Event $event)
    {

        $request->validate([
            'name' => 'required' ,
            'Location'=> 'required',
            'Starts' => 'required',
            'Ends' => 'required',
            'Image'=> 'required' ,
            'Description'=> 'required' ,
            'OrganiserName'=> 'required' ,
            'OrganiserDescription'=> 'required' ,
            'EventCategoryId'=> 'required' ,
            'EventTopicId'=> 'required' ,
        
        ]);

        $event->update($request->all());

        return redirect()->route('event.index')
            ->with('success','event updated successfully');
    }
   
  
     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
  
   
    public function destroy(Event $event)

    {
          
          $event->delete();
       
        return redirect()->route('event.index')
         ->with('success' ,'Successfully deleted the Event!');
    }
}
   

laravel CRUD/resources/views/event/create.blade.php
@extends('layout')
@section('content')  

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New event</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('event.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div> 
@endif

<form action="{{ route('event.store') }}" method="POST">
    @csrf   
    
     <div class="row">   
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group"> 
            <div> 
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name"> 
                </div>
                <div>
                <strong>Location:</strong>
                <input type="text" name="Location" class="form-control" placeholder="Location">
                </div>
                <div>
                <strong>Starts:</strong>
                <input type="datetime" name="Starts" class="form-control" placeholder="Starts">
                </div>
                <div>
                <strong>Ends:</strong>
                <input type="datetime" name="Ends" class="form-control" placeholder="Ends">
                </div>
                <div>
                <strong>Image:</strong>
                <input type="text" name="Image" class="form-control" placeholder="Image">
                </div>
                <div>
                <strong>Description:</strong>
                <input type="text" name="Description" class="form-control" placeholder="Description">
                </div>
                <div>
                <strong>OrganiserName:</strong>
                <input type="text" name="OrganiserName" class="form-control" placeholder="OrganiserName">
                </div>
                <div>
                <strong>OrganiserDescription:</strong>
                <input type="text" name="OrganiserDescription" class="form-control" placeholder="OrganiserDescription">
                </div>
                <div>
                <label for="EventCategoryId">Event categorie</label>
                <select required id="EventCategoryId" name="EventCategoryId" >
                    <!-- option elementen --> 
                @foreach ($eventcategory as $eventcategory) 
            <option value= "{{ $eventcategory->id }}" >  {{ $eventcategory->name }} </option>
            @endforeach
                </select>                
                
               
                </div>  
                <div>
                <label for="EventTopicId">EventTopic Id</label>
                <select required id="EventTopicId" name="EventTopicId" >
                    <!-- option elementen --> 
                @foreach ($eventtopic as $eventtopic) 
            <option value= "{{ $eventtopic->id }}" >  {{ $eventtopic->name }} </option>
            @endforeach
                </select>                
                
               
                </div>
        </div> 
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

laravel CRUD/resources/views/event/index.blade.php
@extends('layout')  



@section('content' ) 

    <div class="row"> 
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 7 CRUD Fric-frac</h2>
               
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('event.create') }}"> Create New Event</a>
                
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Name</th>
           

            <th width="280px">Action</th>
        </tr>
        @foreach ($event as $item)
        <tr>
            <td>{{ $item->id }}</td>
            <td>{{ $item->name }}</td>
          
            
            <td>


            <form action="{{ route('event.destroy',$item->id) }}" method="POST">


<a class="btn btn-info" href="{{ route('event.show',$item->id) }}">Show</a>


<a class="btn btn-primary"  href="{{ route('event.edit' ,$item->id) }}">Edit </a>

@csrf
@method('DELETE')

<button type="submit" class="btn btn-danger">Delete</button>
</form>

</td>
        </tr>
        @endforeach
    </table>
 @endsection

laravel CRUD/resources/views/event/readingone.blade.php
@extends('layout')
@section('content') 

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Reading: {{ $event->name }}</h2> 
       </div> 
       <br>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('event.index') }}"> Back</a>
        </div>
    </div>
</div> 

<table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Location</th>
            <th>Starts</th>
            <th>Ends</th>
            <th>Image</th>
            <th>Description</th>
            <th>OrganiserName</th>
            <th>OrganiserDescription</th>
            <th>EventCategoryId</th>
            <th>EventTopicId</th>
           
        </tr> 

        <td>{{ $event->id }}</td>
            <td>{{ $event->name }}</td> 
            <td>{{ $event->Location }}</td>
            <td>{{ $event->Starts }}</td>
            <td>{{ $event->Ends }}</td>
            <td>{{ $event->Image }}</td>
            <td>{{ $event->Description }}</td>
            <td>{{ $event->OrganiserName }}</td>
            <td>{{ $event->OrganiserDescription }}</td>
            <td>{{ $event->EventCategoryId }}</td>
            <td>{{ $event->EventTopicId }}</td>
        
    </div>
    </table>
    @endsection

laravel CRUD/resources/views/event/updateone.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Event</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('event.index') }}"> Back</a>
        </div>
    </div>
</div> 

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('event.update' , $event->id) }}" method="POST">
    @csrf
    @method('PUT')
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            
            <div>
                <strong>Name:</strong>
               
                <input type="text" name="name" class="form-control"  value="{{ $event->name }}">
            </div>
            <div>
                <strong>Location:</strong>
                <input type="text" name="Location" class="form-control" value="{{ $event->Location }}">
                </div>
                <div>
                <strong>Starts:</strong>
                <input type="datetime" name="Starts" class="form-control" value="{{ $event->Starts }}">
                </div>
                <div>
                <strong>Ends:</strong>
                <input type="datetime" name="Ends" class="form-control" value="{{ $event->Ends }}">
                </div>
                <div>
                <strong>Image:</strong>
                <input type="text" name="Image" class="form-control" value="{{ $event->Image }}">
                </div>
                <div>
                <strong>Description:</strong>
                <input type="text" name="Description" class="form-control" value="{{ $event->Description }}">
                </div>
                <div>
                <strong>OrganiserName:</strong>
                <input type="text" name="OrganiserName" class="form-control" value="{{ $event->OrganiserName }}">
                </div>
                <div>
                <strong>OrganiserDescription:</strong>
                <input type="text" name="OrganiserDescription" class="form-control" value="{{ $event->OrganiserDescription }}">

                </div>
                <div>
                <strong>EventCategory:</strong>
                <input type="text" name="EventCategoryId" class="form-control" value="{{ $event->EventCategoryId }}" readonly>
                
                </div>
                <div>
                <strong>EventTopicId:</strong>
                <input type="text" name="EventTopicId" class="form-control" value="{{ $event->EventTopicId }}" readonly >
                
                </div>
              
                </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection